# Generated by Django 4.0.10 on 2024-06-05 22:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendor', '0001_initial'),
        ('store', '0005_cartorder_stripe_session_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='CartItem',
        ),
        migrations.RenameModel(
            old_name='CartOrder',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='CartOrderItem',
            new_name='OrderItem',
        ),
        migrations.DeleteModel(
            name='ProductVariation',
        ),
    ]
